### ISSUE TITLE
Humidity Monitor Plugin Activation Failed

### ISSUE THREAD

**Issue by garudaonekh** [martinpihrt/OSPy-plugins#9]
Hi,
when I activate the Humidity plugin, it's back to off. I remove and reinstall it but still the same. All other plugins are ok.
Please note that I activate all the plugins successfully, except this one.

Thanks;

**Comment by martinpihrt** [comment]
Hi,
this plugin is not finished (is under development) and therefore does not work now.
Martin

**Comment by garudaonekh** [comment]
What's left for this sensor? Maybe I can look for workaround with the coding. It's important for me.
By the way, does it support multiple soil moisture sensor? For example, 1 sensor for a group of 8 stations...

**Comment by martinpihrt** [comment]
Here is documentation:
https://pihrt.com/elektronika/339-moje-raspberry-pi-plugin-ospy-vlhkost-pudy-a-mozstvi-vody-v-tankua

hardware is ready for 8 stations (8 inputs from Atmega328). The principle is that the processor measures the frequencys from the probes. The probe changes the frequency according to humidity (the dielectric of the capacitor is different when dry and different when wet). The Atmega is connected via the I2C bus to the OSPy. In OSPy, this plugin reads I2C and displays frequencies that are mapped to a range of 0-100%.

So it's not done at the moment:
OSPy plugin only reads and displays frequency from I2C (from atmega328)
the probe with NE555 is not reliable. It is not temperature compensated. The more I got into the problem, the more difficult it became for me to solve it somehow. The biggest problem is how to reliably obtain information about humidity (sensor).
In addition, I then started thinking about wireless sensors (because how will I pull OSPy cables with probe - it would probably go, for example, via RS485 ...)
That's why I postponed the plugin, because I dealt with a lot of other modifications.
I would also like to finish it. If you join I will be happy.

Using a method other than TDR or FDR makes no sense at all (for example 2 electrodes and measuring soil resistance, or probe  extensions for Arduino) ...
https://github.com/martinpihrt/OSPy-plugins/blob/master/plugins/humi_monitor/__init__.py

**Comment by martinpihrt** [comment]
[sensors-18-01648.pdf](https://github.com/martinpihrt/OSPy-plugins/files/6952313/sensors-18-01648.pdf)
[sensors-19-00491.pdf](https://github.com/martinpihrt/OSPy-plugins/files/6952314/sensors-19-00491.pdf)

**Comment by martinpihrt** [comment]
Industrially available sensors are quite expensive and I wanted to do my own for different garden zones. For example, I don't want to buy 10 sensors each for $ 200

**Comment by garudaonekh** [comment]
![IMG_20210809_133444](https://user-images.githubusercontent.com/2074857/128667986-3c2dc769-debf-4774-bc99-1926f54bbc4c.jpg)
True! soil moistuere is hard to do and unreliable. I am testing several capacitive model. The most reliable one so far is by DFRobot.

**Comment by martinpihrt** [comment]
Great, if you find a reliable measurement method, then let me know - I'll connect it to OSPy.
Maybe then I'll get this sensor in our country in the Czech Republic (if it's the right one)
